"use client";

import Header from "@/components/Header";
import "./globals.css";
import Option from "./option";
import { HeaderItems } from "@/constants";
import Footer from "@/components/Footer";
import React, { useEffect } from "react";
import { MyProvider, jotaiStore } from "../jotai/state-provider";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const setHeaderColorAtom = useSetAtom(headerColorAtom);
  // const [header, setHeaderColorAtom] = useAtom(headerColorAtom);

  return (
    <html lang="en">
      <body className="">
        <MyProvider>
          <Option />
          <Header headerItems={HeaderItems} fixed />
          <div
            className="z-10 relative"
            // {css({ zIndex: 10 })}
          >
            {children}
          </div>
          <Footer />
        </MyProvider>
      </body>
    </html>
  );
}
